services:
  mongodb:
    image: mongo
    container_name: node-mongo-laudo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  node_app:
    container_name: node-app-laudo
    build: .
    ports:
      - 4000:4000
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    depends_on:
      - mongodb
    env_file:
      - .env

volumes:
  mongo: # volume para os mongo

